version: 2
jobs:
    build:
        docker:
            - image: rpseq/docker-latex
        steps:
            - checkout
            - run:
                name: config
                command: |
                    git config --global user.email "ryan.smith.p@gmail.com"
                    git config --global user.name "RPSeq"
            - run:
                name: clean
                command: |
                    rm ryan_p_smith_resume.pdf
                    rm ryan_p_smith_resume.png
            - run:
                name: makePDF
                command: latexmk -pdf ryan_p_smith_resume.tex
            - run:
                name: makePNG
                command: convert -density 300 ryan_p_smith_resume.pdf -quality 90 -flatten ryan_p_smith_resume.png
            - run:
                name: push
                command: |
                    git commit -am "Auto-build $CIRCLE_BUILD_NUM [ci skip]"
                    git push --set-upstream origin devops
